name: takeaway_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  equatable: any
  json_annotation: any
  freezed_annotation: any

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.2
  provider: ^6.1.2
  font_awesome_flutter: ^10.7.0
  smooth_page_indicator: ^1.1.0
  pinput: ^4.0.0
  http: ^1.2.1
  animated_text_kit: ^4.2.2
  shimmer: ^3.0.0
  url_launcher: ^6.2.5
  awesome_snackbar_content: ^0.1.3
  mobile_scanner: ^4.0.1
  flutter_snake_navigationbar: ^0.6.1
  #image_picker: ^1.0.7


dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: any
  build_runner: any
  freezed: any

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/gif/
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-MediumItalic.ttf
        - asset: fonts/Poppins-Medium.ttf
        - asset: fonts/Poppins-LightItalic.ttf
        - asset: fonts/Poppins-Light.ttf
        - asset: fonts/Poppins-Italic.ttf
        - asset: fonts/Poppins-Bold.ttf
        - asset: fonts/Poppins-BoldItalic.ttf
          weight: 700  
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
